### ISSUE TITLE
Does this use require computer configuration? I used it the same way as the blueprint node is connected. This will cause UE4 to get stuck

### ISSUE THREAD

**Issue by Lemondogdog** [gtreshchev/RuntimeSpeechRecognizer#2] opened 2023-04-03 11:34 UTC
Does this use require computer configuration? I used it the same way as the blueprint node is connected. This will cause UE4 to get stuck

**Comment by gtreshchev** [comment] 2023-04-03 14:51
It can stack when closing the editor while running a background worker for speech recognition, until the thread ends. If this is your case, then this is the intended behavior to ensure that the thread has completely finished running at the time of closing. Is this what you mean? Also, if you could send your logs, it would be great.

**Closed as completed** 2023-04-06 11:49 UTC
