### ISSUE TITLE
LanguageModel object already exist prompt appears on every editor startup

### ISSUE THREAD

**Issue by rlewicki** [gtreshchev/RuntimeSpeechRecognizer#15] opened 2023-09-25 09:11 UTC
Hi, I've noticed that after initial boot up after a selected language model has been downloaded and then `LanguageModel.uasset` created, every time I restart the editor I get the prompt about the asset already existing, asking whether I want to replace it or not. If I select no, new window will show saying that `RuntimeSpeechRecognizer` cannot function correctly because the language model asset could not be created.

I think there is an issue with the editor code not being able to detect whether the language model asset already exist or not and it's attempting on creating it from scratch regardless.

Unreal Engine version: 5.0.3
Plugin version: 1.0 (this is version specified in `.uplugin`  file, this is latest from the marketplace)

**Comment by gtreshchev** [comment] 2023-09-30 11:19
The intended behavior is to synchronize the language model asset on each startup to ensure that the language model file is always the same as the previously downloaded one. Anyway, thanks for letting me know, this should be fixed in commit 271fe7e.

**Closed as completed** 2023-09-30 11:19 UTC

**Comment by rlewicki** [comment] 2023-10-01 10:06
Great to hear, very glad this got fixed properly 👍
